import { test, expect } from '@playwright/test';
import { E2E_API_BASE_URL, E2E_WEB_ORIGIN } from './urls';
const api = E2E_API_BASE_URL;
const password = 'RentPay-Integration-2026!';
async function latestToken(request: import('@playwright/test').APIRequestContext, recipient: string, event: string) {
 const response = await request.get(`${api}/dev/mailbox`);
 const messages = await response.json() as Array<{ recipient: string; event: string; text: string }>;
 const email = messages.reverse().find((item) => item.recipient === recipient && item.event === event);
 expect(email).toBeTruthy();
 return new URL(email!.text.match(/https?:\/\/\S+/)![0]).searchParams.get('token')!;
}
async function login(request: import('@playwright/test').APIRequestContext, email: string, kind = 'BUSINESS') {
 const response = await request.post(`${api}/auth/login`, { data: { email, password, accountType: kind } });
 expect(response.ok()).toBeTruthy();
 return await response.json() as { accessToken: string; user: { businessId?: string } };
}
test('Phase 1 auth, tenancy, platform boundary and subscription approval', async ({ request, page }) => {
 expect((await request.get(`${api}/business/fleet`)).status()).toBe(401);
 const stamp = Date.now();
 const ownerA = `owner-a-${stamp}@example.test`;
 const ownerB = `owner-b-${stamp}@example.test`;
 const register = (email: string, name: string) => request.post(`${api}/auth/register`, { data: { email, password, businessName: name, name: 'Phase One Tester', termsAccepted: true } });
 const regA = await register(ownerA, 'Example Fleet A');
 const regB = await register(ownerB, 'Example Fleet B');
 expect(regA.status()).toBe(201); expect(regB.status()).toBe(201);
 const a = await regA.json() as { businessId: string };
 const b = await regB.json() as { businessId: string };
 await expect.poll(async () => (await request.get(`${api}/dev/mailbox`)).status()).toBe(200);
 const verifyA = await latestToken(request, ownerA, 'EMAIL_VERIFICATION');
 const verifyB = await latestToken(request, ownerB, 'EMAIL_VERIFICATION');
 expect((await request.post(`${api}/auth/verify-email`, { data: { token: verifyA } })).status()).toBe(204);
 expect((await request.post(`${api}/auth/verify-email`, { data: { token: verifyB } })).status()).toBe(204);
 const tokenA = await login(request, ownerA);
 const tokenB = await login(request, ownerB);
 const headersA = { authorization: `Bearer ${tokenA.accessToken}`, 'x-business-id': a.businessId };
 const headersB = { authorization: `Bearer ${tokenB.accessToken}`, 'x-business-id': b.businessId };
 const trialResponse = await request.get(`${api}/business/subscription`, { headers: headersA });
 const trial = await trialResponse.json() as { status: string; trialStartedAt: string; trialEndsAt: string };
 expect(trial.status).toBe('TRIALING');
 expect(new Date(trial.trialEndsAt).getTime() - new Date(trial.trialStartedAt).getTime()).toBe(30 * 86400000);
 const fleetAResponse = await request.post(`${api}/business/fleet`, { headers: headersA, data: { make: 'Toyota', model: 'Corolla', registrationNumber: `LEA-${stamp}`, dailyRateMinor: 1250000, businessId: b.businessId } });
 expect(fleetAResponse.status()).toBe(201);
 const vehicleA = await fleetAResponse.json() as { id: string; businessId?: string; registrationNumber: string };
 expect(vehicleA.registrationNumber).toBe(`LEA-${stamp}`);
 expect(vehicleA.businessId).toBeUndefined();
 const vehicleBResponse = await request.post(`${api}/business/fleet`, { headers: headersB, data: { make: 'Honda', model: 'City', registrationNumber: `LEB-${stamp}`, dailyRateMinor: 950000 } });
 expect(vehicleBResponse.status()).toBe(201);
 const vehicleB = await vehicleBResponse.json() as { id: string };
 const todayAResponse = await request.get(`${api}/business/operations/today`, { headers: headersA });
 const todayBResponse = await request.get(`${api}/business/operations/today`, { headers: headersB });
 expect(todayAResponse.status()).toBe(200); expect(todayBResponse.status()).toBe(200);
 expect((await todayAResponse.json() as { availableVehicles: number }).availableVehicles).toBe(1);
 expect((await todayBResponse.json() as { availableVehicles: number }).availableVehicles).toBe(1);
 expect((await request.get(`${api}/business/operations/today`, { headers: { ...headersA, 'x-business-id': b.businessId } })).status()).toBe(403);
 const fleetListA = await request.get(`${api}/business/fleet`, { headers: headersA });
 expect((await fleetListA.json()).map((vehicle: { id: string }) => vehicle.id)).toEqual([vehicleA.id]);
 expect((await request.get(`${api}/business/fleet/${vehicleB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/fleet/${vehicleB.id}`, { headers: headersA, data: { make: 'Stolen' } })).status()).toBe(404);
 expect((await request.delete(`${api}/business/fleet/${vehicleB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/fleet/guessed-cross-tenant-id`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/fleet/${vehicleB.id}`, { headers: headersB })).status()).toBe(200);
 const locationAResponse = await request.post(`${api}/business/locations`, { headers: headersA, data: { name: `A Pickup ${stamp}`, timezone: 'Asia/Karachi', address: 'Tenant A address', businessId: b.businessId } });
 const locationBResponse = await request.post(`${api}/business/locations`, { headers: headersB, data: { name: `B Pickup ${stamp}`, timezone: 'Asia/Karachi', address: 'Tenant B address' } });
 expect(locationAResponse.status()).toBe(201); expect(locationBResponse.status()).toBe(201);
 const locationA = await locationAResponse.json() as { id: string; businessId?: string };
 const locationB = await locationBResponse.json() as { id: string };
 expect(locationA.businessId).toBeUndefined();
 const locationsAResponse = await request.get(`${api}/business/locations`, { headers: headersA });
 expect((await locationsAResponse.json() as Array<{ id: string }>).map((row) => row.id)).toEqual([locationA.id]);
 expect((await request.get(`${api}/business/locations/${locationB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/locations/${locationB.id}`, { headers: headersA, data: { address: 'Unauthorized edit' } })).status()).toBe(404);
 expect((await request.delete(`${api}/business/locations/${locationB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/locations/guessed-cross-tenant-id`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/locations/${locationB.id}`, { headers: headersB })).status()).toBe(200);
 expect((await request.patch(`${api}/business/locations/${locationA.id}`, { headers: headersA, data: { phone: '+923001234567' } })).status()).toBe(200);
 const assignedVehicle = await request.post(`${api}/business/fleet`, { headers: headersA, data: { make: 'Location', model: 'Guard Test', registrationNumber: `LOC-${stamp}`, dailyRateMinor: 1000, locationId: locationA.id } });
 expect(assignedVehicle.status()).toBe(201);
 expect((await request.delete(`${api}/business/locations/${locationA.id}`, { headers: headersA })).status()).toBe(409);
 const assignedVehicleId = (await assignedVehicle.json() as { id: string }).id;
 expect((await request.delete(`${api}/business/fleet/${assignedVehicleId}`, { headers: headersA })).status()).toBe(200);
 expect((await request.delete(`${api}/business/locations/${locationA.id}`, { headers: headersA })).status()).toBe(200);
 expect((await request.get(`${api}/business/locations/${locationA.id}`, { headers: headersA })).status()).toBe(404);
 const customerAResponse = await request.post(`${api}/business/customers`, { headers: headersA, data: { fullName: `Customer A ${stamp}`, email: `renter-a-${stamp}@example.test`, phone: '+923001112233', businessId: b.businessId } });
 const customerBResponse = await request.post(`${api}/business/customers`, { headers: headersB, data: { fullName: `Customer B ${stamp}`, email: `renter-b-${stamp}@example.test`, phone: '+923004445566' } });
 expect(customerAResponse.status()).toBe(201); expect(customerBResponse.status()).toBe(201);
 const customerA = await customerAResponse.json() as { id: string; businessId?: string };
 const customerB = await customerBResponse.json() as { id: string };
 expect(customerA.businessId).toBeUndefined();
 const driverBResponse = await request.post(`${api}/business/customers/${customerB.id}/drivers`, { headers: headersB, data: { fullName: 'Tenant B Driver', phone: '+923007778899', licenseNumber: `LIC-${stamp}`, licenseCountry: 'PK' } });
 expect(driverBResponse.status()).toBe(201);
 const driverB = await driverBResponse.json() as { id: string };
 const customerListA = await (await request.get(`${api}/business/customers`, { headers: headersA })).json() as Array<{ id: string }>;
 expect(customerListA.map((customer) => customer.id)).toEqual([customerA.id]);
 expect((await request.get(`${api}/business/customers/${customerB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/customers/${customerB.id}`, { headers: headersA, data: { fullName: 'Unauthorized' } })).status()).toBe(404);
 expect((await request.delete(`${api}/business/customers/${customerB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/customers/guessed-customer-id`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/customers/${customerB.id}/drivers/${driverB.id}`, { headers: headersA, data: { verification: 'VERIFIED' } })).status()).toBe(404);
 expect((await request.delete(`${api}/business/customers/${customerB.id}/drivers/${driverB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.post(`${api}/business/customers/${customerB.id}/drivers`, { headers: headersA, data: { fullName: 'Cross Tenant Driver', phone: '+923001010101' } })).status()).toBe(404);
 expect((await request.get(`${api}/business/customers/${customerB.id}`, { headers: headersB })).status()).toBe(200);
 expect((await request.get(`${api}/business/customers/${customerA.id}`, { headers: headersA })).status()).toBe(200);
 expect((await request.patch(`${api}/business/customers/${customerA.id}`, { headers: headersA, data: { verification: 'VERIFIED' } })).status()).toBe(200);
 expect((await request.get(`${api}/platform/health`, { headers: headersA })).status()).toBe(403);
 const customerEmail = `customer-${stamp}@example.test`;
 expect((await request.post(`${api}/auth/customer/register`, { data: { email: customerEmail, password } })).status()).toBe(201);
 const customerVerifyToken = await latestToken(request, customerEmail, 'EMAIL_VERIFICATION');
 expect((await request.post(`${api}/auth/verify-email`, { data: { token: customerVerifyToken } })).status()).toBe(204);
 const customer = await login(request, customerEmail, 'CUSTOMER');
 expect((await request.get(`${api}/business/fleet`, { headers: { authorization: `Bearer ${customer.accessToken}` } })).status()).toBe(403);
 expect((await request.get(`${api}/business/customers`, { headers: { authorization: `Bearer ${customer.accessToken}` } })).status()).toBe(403);
 expect((await request.get(`${api}/customer/me`, { headers: { authorization: `Bearer ${customer.accessToken}` } })).status()).toBe(200);
 const platformLogin = await request.post(`${api}/auth/login`, { data: { email: 'admin@rentpay.local', password: process.env.SEED_ADMIN_PASSWORD ?? 'RentPay-Local-Only-2026!', accountType: 'PLATFORM' } });
 const platform = await platformLogin.json() as { accessToken: string };
 expect(platformLogin.ok()).toBeTruthy();
 expect((await request.get(`${api}/platform/health`, { headers: { authorization: `Bearer ${platform.accessToken}` } })).status()).toBe(200);
 expect((await request.get(`${api}/business/fleet`, { headers: { authorization: `Bearer ${platform.accessToken}` } })).status()).toBe(403);
 expect((await request.get(`${api}/business/customers`, { headers: { authorization: `Bearer ${platform.accessToken}` } })).status()).toBe(403);
 const planKey = `E2E_${stamp}`;
 const planResponse = await request.post(`${api}/platform/plans`, { headers: { authorization: `Bearer ${platform.accessToken}` }, data: { key: planKey, name: 'Integration plan', amountMinor: 500000, currency: 'PKR' } });
 expect(planResponse.status()).toBe(201);
 const selectedPlan = await planResponse.json() as { id: string; key: string; amountMinor: number };
 const availablePlans = await request.get(`${api}/business/subscription/plans`, { headers: headersA });
 expect((await availablePlans.json()).map((item: { id: string }) => item.id)).toContain(selectedPlan.id);
 const methods = await request.get(`${api}/business/subscription/payment-methods`, { headers: headersA });
 expect((await methods.json()).find((item: { method: string }) => item.method === 'EASYPAISA')?.configured).toBe(true);
 expect((await request.get(`${api}/platform/subscription-payments/pending`, { headers: { authorization: `Bearer ${tokenA.accessToken}` } })).status()).toBe(403);
 const paymentResponse = await request.post(`${api}/business/subscription/payments`, { headers: headersA, data: { method: 'EASYPAISA', planId: selectedPlan.id, reference: `ref-${stamp}` } });
 expect(paymentResponse.status()).toBe(201);
 const payment = await paymentResponse.json() as { id: string };
 expect((await request.patch(`${api}/platform/subscription-payments/${payment.id}/review`, { headers: { authorization: `Bearer ${platform.accessToken}` }, data: { approve: true } })).status()).toBe(200);
 const activatedSubscription = await (await request.get(`${api}/business/subscription`, { headers: headersA })).json() as { status: string; plan: { key: string } };
 expect(activatedSubscription.status).toBe('ACTIVE');
 expect(activatedSubscription.plan.key).toBe(planKey);
 const forgot = await request.post(`${api}/auth/forgot-password`, { data: { email: ownerA } });
 expect(forgot.status()).toBe(202);
 const resetToken = await latestToken(request, ownerA, 'PASSWORD_RESET');
 expect((await request.post(`${api}/auth/reset-password`, { data: { token: resetToken, password } })).status()).toBe(204);
 expect((await request.post(`${api}/auth/reset-password`, { data: { token: resetToken, password } })).status()).toBe(401);
 const refreshedOwner = await login(request, ownerA);
 headersA.authorization = `Bearer ${refreshedOwner.accessToken}`;
 const roleResponse = await request.get(`${api}/business/team/invitation-roles`, { headers: headersA });
 const roles = await roleResponse.json() as Array<{ id: string; key: string }>;
 const inviteRole = roles.find((role) => role.key === 'OPERATIONS_MANAGER')!;
 const inviteEmail = `staff-${stamp}@example.test`;
 expect((await request.post(`${api}/business/invitations`, { headers: headersA, data: { email: inviteEmail, roleId: inviteRole.id } })).status()).toBe(201);
 const inviteToken = await latestToken(request, inviteEmail, 'INVITATION');
 expect((await request.post(`${api}/auth/invite/accept`, { data: { token: inviteToken, password } })).status()).toBe(201);
 const staff = await login(request, inviteEmail);
 expect(staff.user.businessId).toBe(a.businessId);
 const staffHeaders = { authorization: `Bearer ${staff.accessToken}`, 'x-business-id': a.businessId };
 expect((await request.get(`${api}/business/fleet`, { headers: staffHeaders })).status()).toBe(200);
 expect((await request.get(`${api}/business/subscription`, { headers: staffHeaders })).status()).toBe(403);
 expect((await request.get(`${api}/business/locations`, { headers: staffHeaders })).status()).toBe(403);
 expect((await request.get(`${api}/business/team/invitation-roles`, { headers: staffHeaders })).status()).toBe(403);
 expect((await request.post(`${api}/auth/logout`, { headers: { authorization: `Bearer ${staff.accessToken}` } })).status()).toBe(204);
 expect((await request.get(`${api}/business/fleet`, { headers: { authorization: `Bearer ${staff.accessToken}`, 'x-business-id': a.businessId } })).status()).toBe(401);
 await page.goto('/login');
 await page.getByLabel('Email').fill(ownerA);
 await page.getByLabel('Password').fill(password);
 await page.getByRole('button', { name: 'Sign in' }).click();
 await expect(page).toHaveURL(/\/dashboard\/onboarding/);
 await expect(page.getByRole('heading', { name: 'Let’s get your rental workspace ready.' })).toBeVisible();
 await page.goto('/logout');
 await page.getByRole('button', { name: 'Sign out' }).click();
 await expect(page).toHaveURL(/\/login/);
 await page.goto('/app/today');
 await expect(page).toHaveURL(/\/login/);
 const publicPage = await page.goto('/');
 expect(publicPage?.headers()['content-security-policy']).toContain("default-src 'self'");
 await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', E2E_WEB_ORIGIN);
 const robots = await request.get(`${E2E_WEB_ORIGIN}/robots.txt`, { timeout: 5000 });
 expect(await robots.text()).toContain('/platform/');
});

test('reservation availability is tenant-scoped and prevents concurrent double booking', async ({ request }) => {
 const stamp = Date.now();
 const ownerA = `reservation-a-${stamp}@example.test`;
 const ownerB = `reservation-b-${stamp}@example.test`;
 for (const [email, businessName] of [[ownerA, `Reservation A ${stamp}`], [ownerB, `Reservation B ${stamp}`]]) {
  expect((await request.post(`${api}/auth/register`, { data: { email, password, businessName, name: 'Reservation Test Owner', termsAccepted: true } })).status()).toBe(201);
 }
 for (const email of [ownerA, ownerB]) {
  const verificationToken = await latestToken(request, email, 'EMAIL_VERIFICATION');
  expect((await request.post(`${api}/auth/verify-email`, { data: { token: verificationToken } })).status()).toBe(204);
 }
 const tokenA = await login(request, ownerA);
 const tokenB = await login(request, ownerB);
 const headersA = { authorization: `Bearer ${tokenA.accessToken}` };
 const headersB = { authorization: `Bearer ${tokenB.accessToken}` };
 const locationA = await request.post(`${api}/business/locations`, { headers: headersA, data: { name: `A Reservation Hub ${stamp}`, timezone: 'Asia/Karachi' } }).then((response) => response.json()) as { id: string };
 const locationB = await request.post(`${api}/business/locations`, { headers: headersB, data: { name: `B Reservation Hub ${stamp}`, timezone: 'Asia/Karachi' } }).then((response) => response.json()) as { id: string };
 const customerA = await request.post(`${api}/business/customers`, { headers: headersA, data: { fullName: `Renter A ${stamp}`, phone: '+923001110001', email: `reservation-renter-a-${stamp}@example.test` } }).then((response) => response.json()) as { id: string };
 const customerB = await request.post(`${api}/business/customers`, { headers: headersB, data: { fullName: `Renter B ${stamp}`, phone: '+923001110002', email: `reservation-renter-b-${stamp}@example.test` } }).then((response) => response.json()) as { id: string };
 expect((await request.patch(`${api}/business/customers/${customerA.id}`, { headers: headersA, data: { verification: 'VERIFIED' } })).status()).toBe(200);
 expect((await request.patch(`${api}/business/customers/${customerB.id}`, { headers: headersB, data: { verification: 'VERIFIED' } })).status()).toBe(200);
 const vehicleA = await request.post(`${api}/business/fleet`, { headers: headersA, data: { make: 'Toyota', model: 'Availability A', registrationNumber: `RESA-${stamp}`, dailyRateMinor: 1250000, depositMinor: 500000, locationId: locationA.id } }).then((response) => response.json()) as { id: string };
 const vehicleB = await request.post(`${api}/business/fleet`, { headers: headersB, data: { make: 'Honda', model: 'Availability B', registrationNumber: `RESB-${stamp}`, dailyRateMinor: 950000, locationId: locationB.id } }).then((response) => response.json()) as { id: string };
 const startAt = new Date(Date.now() + 10 * 86400000);
 const endAt = new Date(startAt.getTime() + 2 * 86400000);
 const reservationPayload = { customerId: customerA.id, vehicleId: vehicleA.id, pickupLocationId: locationA.id, startAt: startAt.toISOString(), endAt: endAt.toISOString(), businessId: tokenB.user.businessId };
 const firstResponse = await request.post(`${api}/business/reservations`, { headers: headersA, data: reservationPayload });
 expect(firstResponse.status()).toBe(201);
 const firstReservation = await firstResponse.json() as { id: string; businessId?: string; estimatedTotalMinor: number; customerName: string };
 expect(firstReservation.businessId).toBeUndefined();
 expect(firstReservation.estimatedTotalMinor).toBe(2500000);
 expect(firstReservation.customerName).toBe(`Renter A ${stamp}`);
 const availabilityParams = new URLSearchParams({ startAt: startAt.toISOString(), endAt: endAt.toISOString(), locationId: locationA.id });
 const availability = await request.get(`${api}/business/availability?${availabilityParams}`, { headers: headersA }).then((response) => response.json()) as { vehicles: Array<{ id: string }> };
 expect(availability.vehicles.map((vehicle) => vehicle.id)).not.toContain(vehicleA.id);
 expect((await request.patch(`${api}/business/reservations/${firstReservation.id}/status`, { headers: headersA, data: { status: 'CONFIRMED' } })).status()).toBe(200);
 expect((await request.patch(`${api}/business/reservations/${firstReservation.id}/status`, { headers: headersA, data: { status: 'READY_FOR_PICKUP' } })).status()).toBe(200);
 const concurrentStart = new Date(endAt.getTime() + 2 * 86400000);
 const concurrentEnd = new Date(concurrentStart.getTime() + 2 * 86400000);
 const concurrentPayload = { ...reservationPayload, startAt: concurrentStart.toISOString(), endAt: concurrentEnd.toISOString() };
 const concurrentResults = await Promise.all([
  request.post(`${api}/business/reservations`, { headers: headersA, data: concurrentPayload }),
  request.post(`${api}/business/reservations`, { headers: headersA, data: concurrentPayload }),
 ]);
 expect(concurrentResults.map((response) => response.status()).sort()).toEqual([201, 409]);
 const reservationBResponse = await request.post(`${api}/business/reservations`, { headers: headersB, data: { ...reservationPayload, customerId: customerB.id, vehicleId: vehicleB.id, pickupLocationId: locationB.id } });
 expect(reservationBResponse.status()).toBe(201);
 const reservationB = await reservationBResponse.json() as { id: string };
 expect((await request.patch(`${api}/business/reservations/${reservationB.id}/status`, { headers: headersB, data: { status: 'CONFIRMED' } })).status()).toBe(200);
 expect((await request.patch(`${api}/business/reservations/${reservationB.id}/status`, { headers: headersB, data: { status: 'READY_FOR_PICKUP' } })).status()).toBe(200);
 const rentalBResponse = await request.post(`${api}/business/reservations/${reservationB.id}/convert-to-rental`, { headers: headersB });
 expect(rentalBResponse.status()).toBe(201);
 const rentalB = await rentalBResponse.json() as { id: string };
 const paymentPath = `${api}/business/reservations/${firstReservation.id}/payments`;
 const depositPath = `${api}/business/reservations/${firstReservation.id}/deposits`;
 expect((await request.post(paymentPath, { headers: headersA, data: { type: 'RECEIVED', amountMinor: 200000, method: 'EASYPAISA', reference: 'TEST-RECEIPT', businessId: tokenB.user.businessId } })).status()).toBe(201);
 expect((await request.post(paymentPath, { headers: headersA, data: { type: 'REFUNDED', amountMinor: 200001, method: 'CASH' } })).status()).toBe(409);
 expect((await request.post(paymentPath, { headers: headersA, data: { type: 'REFUNDED', amountMinor: 50000, method: 'BANK_TRANSFER', reference: 'TEST-REFUND' } })).status()).toBe(201);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'COLLECTED', amountMinor: 400000, reason: 'Collected at pickup' } })).status()).toBe(201);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'REFUNDED', amountMinor: 400001, reason: 'Over-balance refund check' } })).status()).toBe(409);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'RETAINED', amountMinor: 100000, reason: 'Late return charge' } })).status()).toBe(201);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'REFUNDED', amountMinor: 200000, reason: 'Remaining deposit returned' } })).status()).toBe(201);
 const ledger = await request.get(`${api}/business/reservations/${firstReservation.id}/ledger`, { headers: headersA }).then((response) => response.json()) as { paymentTotalMinor: number; depositHeldMinor: number };
 expect(ledger.paymentTotalMinor).toBe(150000);
 expect(ledger.depositHeldMinor).toBe(100000);
 const ownList = await request.get(`${api}/business/reservations`, { headers: headersA }).then((response) => response.json()) as Array<{ id: string }>;
 expect(ownList.map((reservation) => reservation.id)).toContain(firstReservation.id);
 expect(ownList.map((reservation) => reservation.id)).not.toContain(reservationB.id);
 expect((await request.get(`${api}/business/reservations/${reservationB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/reservations/${reservationB.id}/ledger`, { headers: headersA })).status()).toBe(404);
 expect((await request.post(`${api}/business/reservations/${reservationB.id}/payments`, { headers: headersA, data: { type: 'RECEIVED', amountMinor: 1000, method: 'CASH' } })).status()).toBe(404);
 expect((await request.get(`${api}/business/rentals`, { headers: headersA })).status()).toBe(200);
 expect((await request.get(`${api}/business/rentals/${rentalB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/reservations/${reservationB.id}/status`, { headers: headersA, data: { status: 'CANCELLED', reason: 'cross tenant check' } })).status()).toBe(404);
 expect((await request.get(`${api}/business/reservations/guessed-reservation-id`, { headers: headersA })).status()).toBe(404);
 expect((await request.post(`${api}/business/reservations`, { headers: headersA, data: { ...reservationPayload, vehicleId: vehicleB.id } })).status()).toBe(404);
 const conversion = await request.post(`${api}/business/reservations/${firstReservation.id}/convert-to-rental`, { headers: headersA });
 expect(conversion.status()).toBe(201);
 const rental = await conversion.json() as { id: string; vehicleId: string; status: string; estimatedTotalMinor: number };
 expect(rental.status).toBe('BOOKED');
 expect((await request.get(`${api}/business/rentals/${rental.id}`, { headers: headersB })).status()).toBe(404);
 expect((await request.patch(`${api}/business/reservations/${firstReservation.id}/status`, { headers: headersA, data: { status: 'CANCELLED', reason: 'Cannot cancel after conversion' } })).status()).toBe(409);
 expect((await request.post(`${api}/business/rentals/${rental.id}/checkout`, { headers: headersA, data: { odometerKm: 12000, fuelPercent: 80 } })).status()).toBe(409);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'COLLECTED', amountMinor: 400000, reason: 'Balance collected before handover' } })).status()).toBe(201);
 const clearChecklist = { exterior: 'OK', glass: 'OK', tires: 'OK', lights: 'OK', interior: 'OK', documents: 'OK', accessories: 'OK' };
 const preHandover = await request.post(`${api}/business/inspections`, { headers: headersA, data: { vehicleId: rental.vehicleId, rentalId: rental.id, stage: 'PRE_HANDOVER', checklist: clearChecklist, odometerKm: 12000, fuelPercent: 80 } });
 expect(preHandover.status()).toBe(201);
 const inspectionA = await preHandover.json() as { id: string };
 expect((await request.get(`${api}/business/inspections?vehicleId=${encodeURIComponent(rental.vehicleId)}`, { headers: headersB }).then((response) => response.json()) as Array<{ id: string }>).length).toBe(0);
 const checkout = await request.post(`${api}/business/rentals/${rental.id}/checkout`, { headers: headersA, data: { odometerKm: 12000, fuelPercent: 80, notes: 'Vehicle handover complete' } });
 expect(checkout.status()).toBe(201);
 expect((await checkout.json() as { status: string }).status).toBe('ACTIVE');
 const conflictingExtension = await request.patch(`${api}/business/rentals/${rental.id}/extension`, { headers: headersA, data: { expectedReturnAt: new Date(concurrentStart.getTime() + 86400000).toISOString(), reason: 'Test overlap prevention' } });
 expect(conflictingExtension.status()).toBe(409);
 const successfulExtension = await request.patch(`${api}/business/rentals/${rental.id}/extension`, { headers: headersA, data: { expectedReturnAt: new Date(endAt.getTime() + 86400000).toISOString(), reason: 'Renter requested one additional day' } });
 expect(successfulExtension.status()).toBe(200);
 const returnInspection = await request.post(`${api}/business/inspections`, { headers: headersA, data: { vehicleId: rental.vehicleId, rentalId: rental.id, stage: 'RETURN', checklist: clearChecklist, odometerKm: 12100, fuelPercent: 70 } });
 expect(returnInspection.status()).toBe(201);
 const checkin = await request.post(`${api}/business/rentals/${rental.id}/return`, { headers: headersA, data: { odometerKm: 12100, fuelPercent: 70, returnLocationId: locationA.id, notes: 'Returned for cleaning and inspection' } });
 expect(checkin.status()).toBe(201);
 const returnedRental = await checkin.json() as { status: string; vehicle: { condition: string }; endOdometerKm: number };
 expect(returnedRental.status).toBe('RETURNED');
 expect(returnedRental.endOdometerKm).toBe(12100);
 expect(returnedRental.vehicle.condition).toBe('PREPARATION');
 expect((await request.post(`${api}/business/rentals/${rental.id}/return`, { headers: headersA, data: { odometerKm: 12100, fuelPercent: 70, returnLocationId: locationA.id } })).status()).toBe(409);
 const damage = await request.post(`${api}/business/inspections/damage-cases`, { headers: headersA, data: { vehicleId: rental.vehicleId, rentalId: rental.id, inspectionId: inspectionA.id, title: 'Windshield chip', description: 'Small chip noticed during inspection.', estimatedMinor: 200000 } });
 expect(damage.status()).toBe(201);
 const damageCase = await damage.json() as { id: string; status: string };
 expect(damageCase.status).toBe('OPEN');
 expect((await request.patch(`${api}/business/inspections/damage-cases/${damageCase.id}`, { headers: headersA, data: { status: 'RESOLVED' } })).status()).toBe(400);
 expect((await request.patch(`${api}/business/inspections/damage-cases/${damageCase.id}`, { headers: headersB, data: { status: 'RESOLVED', resolutionNotes: 'Cross-tenant' } })).status()).toBe(404);
 expect((await request.patch(`${api}/business/inspections/damage-cases/${damageCase.id}`, { headers: headersA, data: { status: 'RESOLVED', resolutionNotes: 'Replaced windshield and checked the seal.' } })).status()).toBe(200);
 const settlementPath = `${api}/business/rentals/${rental.id}/settlement`;
 expect((await request.post(settlementPath, { headers: headersB, data: { additionalChargesMinor: 0, paymentReceivedMinor: 3_000_000, method: 'CASH' } })).status()).toBe(404);
 expect((await request.post(settlementPath, { headers: headersA, data: { additionalChargesMinor: 0, paymentReceivedMinor: 3_000_000, method: 'CASH' } })).status()).toBe(409);
 const settlement = await request.post(settlementPath, { headers: headersA, data: { additionalChargesMinor: 0, paymentReceivedMinor: 3_350_000, method: 'CASH', note: 'Rental balance received in full.' } });
 expect(settlement.status()).toBe(201);
 expect(await settlement.json()).toMatchObject({ rentalAmountMinor: 3_750_000, paymentReceivedMinor: 3_350_000, depositRetainedMinor: 250_000, depositRefundedMinor: 250_000 });
 expect((await request.get(`${api}/business/rentals/${rental.id}`, { headers: headersA }).then((response) => response.json()) as { status: string }).status).toBe('CLOSED');
 expect((await request.post(settlementPath, { headers: headersA, data: { additionalChargesMinor: 0, paymentReceivedMinor: 0, method: 'CASH' } })).status()).toBe(409);
 const issueChecklist = { ...clearChecklist, glass: 'ISSUE' };
 const issueInspection = await request.post(`${api}/business/inspections`, { headers: headersA, data: { vehicleId: rental.vehicleId, stage: 'RETURN', checklist: issueChecklist, odometerKm: 12100, fuelPercent: 70, notes: 'Small glass chip found.' } });
 expect(issueInspection.status()).toBe(201);
 const openCasesA = await request.get(`${api}/business/inspections/damage-cases`, { headers: headersA }).then((response) => response.json()) as Array<{ status: string }>;
 const openCasesB = await request.get(`${api}/business/inspections/damage-cases`, { headers: headersB }).then((response) => response.json()) as Array<{ status: string }>;
 expect(openCasesA.some((entry) => entry.status === 'OPEN')).toBe(true);
 expect(openCasesB).toHaveLength(0);
 expect((await request.get(`${api}/business/reservations`, { headers: { authorization: `Bearer ${tokenB.accessToken}` } })).status()).toBe(200);
});
