import { test, expect } from '@playwright/test';
import { E2E_API_BASE_URL, E2E_WEB_ORIGIN } from './urls';
const api = E2E_API_BASE_URL;
const password = 'RentPay-Integration-2026!';
async function latestToken(request: import('@playwright/test').APIRequestContext, recipient: string, event: string) {
 const response = await request.get(`${api}/dev/mailbox`);
 const messages = await response.json() as Array<{ recipient: string; event: string; text: string }>;
 const email = messages.reverse().find((item) => item.recipient === recipient && item.event === event);
 expect(email).toBeTruthy();
 return new URL(email!.text.match(/https?:\/\/\S+/)![0]).searchParams.get('token')!;
}
async function login(request: import('@playwright/test').APIRequestContext, email: string, kind = 'BUSINESS') {
 const response = await request.post(`${api}/auth/login`, { data: { email, password, accountType: kind } });
 expect(response.ok()).toBeTruthy();
 return await response.json() as { accessToken: string; user: { businessId?: string } };
}
test('Phase 1 auth, tenancy, platform boundary and subscription approval', async ({ request, page }) => {
 expect((await request.get(`${api}/business/fleet`)).status()).toBe(401);
 const stamp = Date.now();
 const ownerA = `owner-a-${stamp}@example.test`;
 const ownerB = `owner-b-${stamp}@example.test`;
 const register = (email: string, name: string) => request.post(`${api}/auth/register`, { data: { email, password, businessName: name, name: 'Phase One Tester', termsAccepted: true } });
 const regA = await register(ownerA, 'Example Fleet A');
 const regB = await register(ownerB, 'Example Fleet B');
 expect(regA.status()).toBe(201); expect(regB.status()).toBe(201);
 const a = await regA.json() as { businessId: string };
 const b = await regB.json() as { businessId: string };
 await expect.poll(async () => (await request.get(`${api}/dev/mailbox`)).status()).toBe(200);
 const verifyA = await latestToken(request, ownerA, 'EMAIL_VERIFICATION');
 const verifyB = await latestToken(request, ownerB, 'EMAIL_VERIFICATION');
 expect((await request.post(`${api}/auth/verify-email`, { data: { token: verifyA } })).status()).toBe(204);
 expect((await request.post(`${api}/auth/verify-email`, { data: { token: verifyB } })).status()).toBe(204);
 const tokenA = await login(request, ownerA);
 const tokenB = await login(request, ownerB);
 const headersA = { authorization: `Bearer ${tokenA.accessToken}`, 'x-business-id': a.businessId };
 const headersB = { authorization: `Bearer ${tokenB.accessToken}`, 'x-business-id': b.businessId };
 const trialResponse = await request.get(`${api}/business/subscription`, { headers: headersA });
 const trial = await trialResponse.json() as { status: string; trialStartedAt: string; trialEndsAt: string };
 expect(trial.status).toBe('TRIALING');
 expect(new Date(trial.trialEndsAt).getTime() - new Date(trial.trialStartedAt).getTime()).toBe(30 * 86400000);
 const fleetAResponse = await request.post(`${api}/business/fleet`, { headers: headersA, data: { make: 'Toyota', model: 'Corolla', registrationNumber: `LEA-${stamp}`, dailyRateMinor: 1250000, businessId: b.businessId } });
 expect(fleetAResponse.status()).toBe(201);
 const vehicleA = await fleetAResponse.json() as { id: string; businessId?: string; registrationNumber: string };
 expect(vehicleA.registrationNumber).toBe(`LEA-${stamp}`);
 expect(vehicleA.businessId).toBeUndefined();
 const vehicleBResponse = await request.post(`${api}/business/fleet`, { headers: headersB, data: { make: 'Honda', model: 'City', registrationNumber: `LEB-${stamp}`, dailyRateMinor: 950000 } });
 expect(vehicleBResponse.status()).toBe(201);
 const vehicleB = await vehicleBResponse.json() as { id: string };
 const todayAResponse = await request.get(`${api}/business/operations/today`, { headers: headersA });
 const todayBResponse = await request.get(`${api}/business/operations/today`, { headers: headersB });
 expect(todayAResponse.status()).toBe(200); expect(todayBResponse.status()).toBe(200);
 expect((await todayAResponse.json() as { availableVehicles: number }).availableVehicles).toBe(1);
 expect((await todayBResponse.json() as { availableVehicles: number }).availableVehicles).toBe(1);
 expect((await request.get(`${api}/business/operations/today`, { headers: { ...headersA, 'x-business-id': b.businessId } })).status()).toBe(403);
 const fleetListA = await request.get(`${api}/business/fleet`, { headers: headersA });
 expect((await fleetListA.json()).map((vehicle: { id: string }) => vehicle.id)).toEqual([vehicleA.id]);
 expect((await request.get(`${api}/business/fleet/${vehicleB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/fleet/${vehicleB.id}`, { headers: headersA, data: { make: 'Stolen' } })).status()).toBe(404);
 expect((await request.delete(`${api}/business/fleet/${vehicleB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/fleet/guessed-cross-tenant-id`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/fleet/${vehicleB.id}`, { headers: headersB })).status()).toBe(200);
 const locationAResponse = await request.post(`${api}/business/locations`, { headers: headersA, data: { name: `A Pickup ${stamp}`, timezone: 'Asia/Karachi', address: 'Tenant A address', businessId: b.businessId } });
 const locationBResponse = await request.post(`${api}/business/locations`, { headers: headersB, data: { name: `B Pickup ${stamp}`, timezone: 'Asia/Karachi', address: 'Tenant B address' } });
 expect(locationAResponse.status()).toBe(201); expect(locationBResponse.status()).toBe(201);
 const locationA = await locationAResponse.json() as { id: string; businessId?: string };
 const locationB = await locationBResponse.json() as { id: string };
 expect(locationA.businessId).toBeUndefined();
 const locationsAResponse = await request.get(`${api}/business/locations`, { headers: headersA });
 expect((await locationsAResponse.json() as Array<{ id: string }>).map((row) => row.id)).toEqual([locationA.id]);
 expect((await request.get(`${api}/business/locations/${locationB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/locations/${locationB.id}`, { headers: headersA, data: { address: 'Unauthorized edit' } })).status()).toBe(404);
 expect((await request.delete(`${api}/business/locations/${locationB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/locations/guessed-cross-tenant-id`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/locations/${locationB.id}`, { headers: headersB })).status()).toBe(200);
 expect((await request.patch(`${api}/business/locations/${locationA.id}`, { headers: headersA, data: { phone: '+923001234567' } })).status()).toBe(200);
 const assignedVehicle = await request.post(`${api}/business/fleet`, { headers: headersA, data: { make: 'Location', model: 'Guard Test', registrationNumber: `LOC-${stamp}`, dailyRateMinor: 1000, locationId: locationA.id } });
 expect(assignedVehicle.status()).toBe(201);
 expect((await request.delete(`${api}/business/locations/${locationA.id}`, { headers: headersA })).status()).toBe(409);
 const assignedVehicleId = (await assignedVehicle.json() as { id: string }).id;
 expect((await request.delete(`${api}/business/fleet/${assignedVehicleId}`, { headers: headersA })).status()).toBe(200);
 expect((await request.delete(`${api}/business/locations/${locationA.id}`, { headers: headersA })).status()).toBe(200);
 expect((await request.get(`${api}/business/locations/${locationA.id}`, { headers: headersA })).status()).toBe(404);
 const customerAResponse = await request.post(`${api}/business/customers`, { headers: headersA, data: { fullName: `Customer A ${stamp}`, email: `renter-a-${stamp}@example.test`, phone: '+923001112233', businessId: b.businessId } });
 const customerBResponse = await request.post(`${api}/business/customers`, { headers: headersB, data: { fullName: `Customer B ${stamp}`, email: `renter-b-${stamp}@example.test`, phone: '+923004445566' } });
 expect(customerAResponse.status()).toBe(201); expect(customerBResponse.status()).toBe(201);
 const customerA = await customerAResponse.json() as { id: string; businessId?: string };
 const customerB = await customerBResponse.json() as { id: string };
 expect(customerA.businessId).toBeUndefined();
 const driverBResponse = await request.post(`${api}/business/customers/${customerB.id}/drivers`, { headers: headersB, data: { fullName: 'Tenant B Driver', phone: '+923007778899', licenseNumber: `LIC-${stamp}`, licenseCountry: 'PK' } });
 expect(driverBResponse.status()).toBe(201);
 const driverB = await driverBResponse.json() as { id: string };
 const customerListA = await (await request.get(`${api}/business/customers`, { headers: headersA })).json() as Array<{ id: string }>;
 expect(customerListA.map((customer) => customer.id)).toEqual([customerA.id]);
 expect((await request.get(`${api}/business/customers/${customerB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/customers/${customerB.id}`, { headers: headersA, data: { fullName: 'Unauthorized' } })).status()).toBe(404);
 expect((await request.delete(`${api}/business/customers/${customerB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/customers/guessed-customer-id`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/customers/${customerB.id}/drivers/${driverB.id}`, { headers: headersA, data: { verification: 'VERIFIED' } })).status()).toBe(404);
 expect((await request.delete(`${api}/business/customers/${customerB.id}/drivers/${driverB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.post(`${api}/business/customers/${customerB.id}/drivers`, { headers: headersA, data: { fullName: 'Cross Tenant Driver', phone: '+923001010101' } })).status()).toBe(404);
 expect((await request.get(`${api}/business/customers/${customerB.id}`, { headers: headersB })).status()).toBe(200);
 expect((await request.get(`${api}/business/customers/${customerA.id}`, { headers: headersA })).status()).toBe(200);
 expect((await request.patch(`${api}/business/customers/${customerA.id}`, { headers: headersA, data: { verification: 'VERIFIED' } })).status()).toBe(200);
 expect((await request.get(`${api}/platform/health`, { headers: headersA })).status()).toBe(403);
 const customerEmail = `customer-${stamp}@example.test`;
 expect((await request.post(`${api}/auth/customer/register`, { data: { email: customerEmail, password } })).status()).toBe(201);
 const customerVerifyToken = await latestToken(request, customerEmail, 'EMAIL_VERIFICATION');
 expect((await request.post(`${api}/auth/verify-email`, { data: { token: customerVerifyToken } })).status()).toBe(204);
 const customer = await login(request, customerEmail, 'CUSTOMER');
 expect((await request.get(`${api}/business/fleet`, { headers: { authorization: `Bearer ${customer.accessToken}` } })).status()).toBe(403);
 expect((await request.get(`${api}/business/customers`, { headers: { authorization: `Bearer ${customer.accessToken}` } })).status()).toBe(403);
 expect((await request.get(`${api}/customer/me`, { headers: { authorization: `Bearer ${customer.accessToken}` } })).status()).toBe(200);
 const platformLogin = await request.post(`${api}/auth/login`, { data: { email: 'admin@rentpay.local', password: process.env.SEED_ADMIN_PASSWORD ?? 'RentPay-Local-Only-2026!', accountType: 'PLATFORM' } });
 const platform = await platformLogin.json() as { accessToken: string };
 expect(platformLogin.ok()).toBeTruthy();
 expect((await request.get(`${api}/platform/health`, { headers: { authorization: `Bearer ${platform.accessToken}` } })).status()).toBe(200);
 expect((await request.get(`${api}/business/fleet`, { headers: { authorization: `Bearer ${platform.accessToken}` } })).status()).toBe(403);
 expect((await request.get(`${api}/business/customers`, { headers: { authorization: `Bearer ${platform.accessToken}` } })).status()).toBe(403);
 const planKey = `E2E_${stamp}`;
 const planResponse = await request.post(`${api}/platform/plans`, { headers: { authorization: `Bearer ${platform.accessToken}` }, data: { key: planKey, name: 'Integration plan', amountMinor: 500000, currency: 'PKR' } });
 expect(planResponse.status()).toBe(201);
 const selectedPlan = await planResponse.json() as { id: string; key: string; amountMinor: number };
 const availablePlans = await request.get(`${api}/business/subscription/plans`, { headers: headersA });
 expect((await availablePlans.json()).map((item: { id: string }) => item.id)).toContain(selectedPlan.id);
 const methods = await request.get(`${api}/business/subscription/payment-methods`, { headers: headersA });
 expect((await methods.json()).find((item: { method: string }) => item.method === 'EASYPAISA')?.configured).toBe(true);
 expect((await request.get(`${api}/platform/subscription-payments/pending`, { headers: { authorization: `Bearer ${tokenA.accessToken}` } })).status()).toBe(403);
 const paymentResponse = await request.post(`${api}/business/subscription/payments`, { headers: headersA, data: { method: 'EASYPAISA', planId: selectedPlan.id, reference: `ref-${stamp}` } });
 expect(paymentResponse.status()).toBe(201);
 await page.goto('/platform/login');
 await page.getByLabel('Email').fill('admin@rentpay.local');
 await page.getByLabel('Password').fill(process.env.SEED_ADMIN_PASSWORD ?? 'RentPay-Local-Only-2026!');
 await page.getByRole('button', { name: 'Sign in' }).click();
 await expect(page).toHaveURL(/\/platform\/access/);
 await expect(page.getByRole('heading', { name: 'Platform overview' })).toBeVisible();
 await expect(page.getByText(`ref-${stamp}`)).toBeVisible();
 await page.getByText(`ref-${stamp}`).locator('xpath=ancestor::article[1]').getByRole('button', { name: 'Approve & activate' }).click();
 await expect(page.getByText(`ref-${stamp}`)).toHaveCount(0);
 const activatedSubscription = await (await request.get(`${api}/business/subscription`, { headers: headersA })).json() as { status: string; plan: { key: string } };
 expect(activatedSubscription.status).toBe('ACTIVE');
 expect(activatedSubscription.plan.key).toBe(planKey);
 const forgot = await request.post(`${api}/auth/forgot-password`, { data: { email: ownerA } });
 expect(forgot.status()).toBe(202);
 const resetToken = await latestToken(request, ownerA, 'PASSWORD_RESET');
 expect((await request.post(`${api}/auth/reset-password`, { data: { token: resetToken, password } })).status()).toBe(204);
 expect((await request.post(`${api}/auth/reset-password`, { data: { token: resetToken, password } })).status()).toBe(401);
 const refreshedOwner = await login(request, ownerA);
 headersA.authorization = `Bearer ${refreshedOwner.accessToken}`;
 const roleResponse = await request.get(`${api}/business/team/invitation-roles`, { headers: headersA });
 const roles = await roleResponse.json() as Array<{ id: string; key: string }>;
 const teamBeforeInvite = await request.get(`${api}/business/team`, { headers: headersA });
 expect(teamBeforeInvite.status()).toBe(200);
 expect((await teamBeforeInvite.json() as { members: Array<{ role: { key: string } }> }).members.some((member) => member.role.key === 'OWNER')).toBeTruthy();
 const inviteRole = roles.find((role) => role.key === 'OPERATIONS_MANAGER')!;
 const inviteEmail = `staff-${stamp}@example.test`;
 expect((await request.post(`${api}/business/invitations`, { headers: headersA, data: { email: inviteEmail, roleId: inviteRole.id } })).status()).toBe(201);
 const inviteToken = await latestToken(request, inviteEmail, 'INVITATION');
 expect((await request.post(`${api}/auth/invite/accept`, { data: { token: inviteToken, password } })).status()).toBe(201);
 const staff = await login(request, inviteEmail);
 expect(staff.user.businessId).toBe(a.businessId);
 const staffHeaders = { authorization: `Bearer ${staff.accessToken}`, 'x-business-id': a.businessId };
 const teamMembers = await request.get(`${api}/business/team`, { headers: headersA }).then((response) => response.json()) as { members: Array<{ id: string; user: { email: string } }> };
 const invitedMember = teamMembers.members.find((member) => member.user.email === inviteEmail)!;
 expect(invitedMember).toBeTruthy();
 expect((await request.patch(`${api}/business/team/${invitedMember.id}`, { headers: headersA, data: { status: 'SUSPENDED' } })).status()).toBe(200);
 expect((await request.get(`${api}/business/fleet`, { headers: staffHeaders })).status()).toBe(403);
 expect((await request.patch(`${api}/business/team/${invitedMember.id}`, { headers: headersA, data: { status: 'ACTIVE' } })).status()).toBe(200);
 expect((await request.get(`${api}/business/fleet`, { headers: staffHeaders })).status()).toBe(200);
 expect((await request.get(`${api}/business/subscription`, { headers: staffHeaders })).status()).toBe(403);
 expect((await request.get(`${api}/business/locations`, { headers: staffHeaders })).status()).toBe(403);
 expect((await request.get(`${api}/business/team/invitation-roles`, { headers: staffHeaders })).status()).toBe(403);
 expect((await request.post(`${api}/auth/logout`, { headers: { authorization: `Bearer ${staff.accessToken}` } })).status()).toBe(204);
 expect((await request.get(`${api}/business/fleet`, { headers: { authorization: `Bearer ${staff.accessToken}`, 'x-business-id': a.businessId } })).status()).toBe(401);
 await page.goto('/login');
 await page.getByLabel('Email').fill(ownerA);
 await page.getByLabel('Password').fill(password);
 await page.getByRole('button', { name: 'Sign in' }).click();
 await expect(page).toHaveURL(/\/dashboard\/onboarding/);
 await expect(page.getByRole('heading', { name: 'Let’s get your rental workspace ready.' })).toBeVisible();
 await page.goto('/app/team');
 await expect(page.getByRole('heading', { name: 'Team', exact: true })).toBeVisible();
 await expect(page.getByRole('heading', { name: 'People with access' })).toBeVisible();
 const invitedUiEmail = `staff-ui-${stamp}@example.test`;
 await page.getByLabel('Work email').fill(invitedUiEmail);
 await page.getByRole('button', { name: 'Send invitation' }).click();
 await expect(page.getByText(`Invitation sent to ${invitedUiEmail}.`)).toBeVisible();
 await expect(page.getByText(invitedUiEmail, { exact: true })).toBeVisible();
 const staffCard = page.locator('article').filter({ hasText: inviteEmail });
 await staffCard.getByRole('button', { name: 'Pause access' }).click();
 await expect(staffCard.getByText('Suspended')).toBeVisible();
 await staffCard.getByRole('button', { name: 'Restore access' }).click();
 await expect(staffCard.getByText('Active')).toBeVisible();
 await page.goto('/logout');
 await page.getByRole('button', { name: 'Sign out' }).click();
 await expect(page).toHaveURL(/\/login/);
 await page.goto('/app/today');
 await expect(page).toHaveURL(/\/login/);
 const publicPage = await page.goto('/');
 expect(publicPage?.headers()['content-security-policy']).toContain("default-src 'self'");
 await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', E2E_WEB_ORIGIN);
 const robots = await request.get(`${E2E_WEB_ORIGIN}/robots.txt`, { timeout: 5000 });
 expect(await robots.text()).toContain('/platform/');
});

test('workspace command search is keyboard accessible and returns authorized tenant records', async ({ request, page }) => {
 const credentials = { email: 'owner@rentpay.local', password: 'RentPay-Local-Only-2026!', accountType: 'BUSINESS' };
 const loginResponse = await request.post(`${api}/auth/login`, { data: credentials });
 expect(loginResponse.ok()).toBeTruthy();
 const session = await loginResponse.json() as { accessToken: string };
 const registrationNumber = `SRCH-${Date.now()}`;
 const createResponse = await request.post(`${api}/business/fleet`, { headers: { authorization: `Bearer ${session.accessToken}` }, data: { make: 'Nissan', model: 'SearchTest', registrationNumber, dailyRateMinor: 100000 } });
 expect(createResponse.status()).toBe(201);

 await page.goto('/login');
 await page.getByLabel('Email').fill(credentials.email);
 await page.getByLabel('Password').fill(credentials.password);
 await page.getByRole('button', { name: 'Sign in' }).click();
 await page.waitForURL(/\/dashboard\/onboarding|\/app\/today/);
 await page.goto('/app/today');
 await page.keyboard.press('Control+k');
 const search = page.getByRole('textbox', { name: 'Search vehicles, customers, bookings and rentals' });
 await expect(search).toBeVisible();
 await search.fill(registrationNumber);
 await expect(page.getByText(registrationNumber)).toBeVisible();
 await expect(page.getByText('Vehicle', { exact: true })).toBeVisible();
});

test('reservation availability is tenant-scoped and prevents concurrent double booking', async ({ request, page }) => {
 const stamp = Date.now();
 const ownerA = `reservation-a-${stamp}@example.test`;
 const ownerB = `reservation-b-${stamp}@example.test`;
 for (const [email, businessName] of [[ownerA, `Reservation A ${stamp}`], [ownerB, `Reservation B ${stamp}`]]) {
  expect((await request.post(`${api}/auth/register`, { data: { email, password, businessName, name: 'Reservation Test Owner', termsAccepted: true } })).status()).toBe(201);
 }
 for (const email of [ownerA, ownerB]) {
  const verificationToken = await latestToken(request, email, 'EMAIL_VERIFICATION');
  expect((await request.post(`${api}/auth/verify-email`, { data: { token: verificationToken } })).status()).toBe(204);
 }
 const tokenA = await login(request, ownerA);
 const tokenB = await login(request, ownerB);
 const headersA = { authorization: `Bearer ${tokenA.accessToken}` };
 const headersB = { authorization: `Bearer ${tokenB.accessToken}` };
 const locationA = await request.post(`${api}/business/locations`, { headers: headersA, data: { name: `A Reservation Hub ${stamp}`, timezone: 'Asia/Karachi' } }).then((response) => response.json()) as { id: string };
 const locationB = await request.post(`${api}/business/locations`, { headers: headersB, data: { name: `B Reservation Hub ${stamp}`, timezone: 'Asia/Karachi' } }).then((response) => response.json()) as { id: string };
 const customerA = await request.post(`${api}/business/customers`, { headers: headersA, data: { fullName: `Renter A ${stamp}`, phone: '+923001110001', email: `reservation-renter-a-${stamp}@example.test` } }).then((response) => response.json()) as { id: string };
 const customerB = await request.post(`${api}/business/customers`, { headers: headersB, data: { fullName: `Renter B ${stamp}`, phone: '+923001110002', email: `reservation-renter-b-${stamp}@example.test` } }).then((response) => response.json()) as { id: string };
 expect((await request.patch(`${api}/business/customers/${customerA.id}`, { headers: headersA, data: { verification: 'VERIFIED' } })).status()).toBe(200);
 expect((await request.patch(`${api}/business/customers/${customerB.id}`, { headers: headersB, data: { verification: 'VERIFIED' } })).status()).toBe(200);
 const vehicleA = await request.post(`${api}/business/fleet`, { headers: headersA, data: { make: 'Toyota', model: 'Availability A', registrationNumber: `RESA-${stamp}`, dailyRateMinor: 1250000, depositMinor: 500000, locationId: locationA.id } }).then((response) => response.json()) as { id: string };
 const vehicleB = await request.post(`${api}/business/fleet`, { headers: headersB, data: { make: 'Honda', model: 'Availability B', registrationNumber: `RESB-${stamp}`, dailyRateMinor: 950000, locationId: locationB.id } }).then((response) => response.json()) as { id: string };
 const startAt = new Date(Date.now() + 10 * 86400000);
 const endAt = new Date(startAt.getTime() + 2 * 86400000);
 const reservationPayload = { customerId: customerA.id, vehicleId: vehicleA.id, pickupLocationId: locationA.id, startAt: startAt.toISOString(), endAt: endAt.toISOString(), businessId: tokenB.user.businessId };
 const firstResponse = await request.post(`${api}/business/reservations`, { headers: headersA, data: reservationPayload });
 expect(firstResponse.status()).toBe(201);
 const firstReservation = await firstResponse.json() as { id: string; businessId?: string; estimatedTotalMinor: number; customerName: string };
 expect(firstReservation.businessId).toBeUndefined();
 expect(firstReservation.estimatedTotalMinor).toBe(2500000);
 expect(firstReservation.customerName).toBe(`Renter A ${stamp}`);
 const availabilityParams = new URLSearchParams({ startAt: startAt.toISOString(), endAt: endAt.toISOString(), locationId: locationA.id });
 const availability = await request.get(`${api}/business/availability?${availabilityParams}`, { headers: headersA }).then((response) => response.json()) as { vehicles: Array<{ id: string }> };
 expect(availability.vehicles.map((vehicle) => vehicle.id)).not.toContain(vehicleA.id);
 expect((await request.patch(`${api}/business/reservations/${firstReservation.id}/status`, { headers: headersA, data: { status: 'CONFIRMED' } })).status()).toBe(200);
 expect((await request.patch(`${api}/business/reservations/${firstReservation.id}/status`, { headers: headersA, data: { status: 'READY_FOR_PICKUP' } })).status()).toBe(200);
 const todayA = await request.get(`${api}/business/operations/today`, { headers: headersA }).then((response) => response.json()) as { pendingPaymentCount: number; pendingPaymentMinor: number };
 const todayB = await request.get(`${api}/business/operations/today`, { headers: headersB }).then((response) => response.json()) as { pendingPaymentCount: number; pendingPaymentMinor: number };
 expect(todayA).toMatchObject({ pendingPaymentCount: 1, pendingPaymentMinor: 2500000 });
 expect(todayB).toMatchObject({ pendingPaymentCount: 0, pendingPaymentMinor: 0 });
 const concurrentStart = new Date(endAt.getTime() + 2 * 86400000);
 const concurrentEnd = new Date(concurrentStart.getTime() + 2 * 86400000);
 const concurrentPayload = { ...reservationPayload, startAt: concurrentStart.toISOString(), endAt: concurrentEnd.toISOString() };
 const concurrentResults = await Promise.all([
  request.post(`${api}/business/reservations`, { headers: headersA, data: concurrentPayload }),
  request.post(`${api}/business/reservations`, { headers: headersA, data: concurrentPayload }),
 ]);
 expect(concurrentResults.map((response) => response.status()).sort()).toEqual([201, 409]);
 const reservationBResponse = await request.post(`${api}/business/reservations`, { headers: headersB, data: { ...reservationPayload, customerId: customerB.id, vehicleId: vehicleB.id, pickupLocationId: locationB.id } });
 expect(reservationBResponse.status()).toBe(201);
 const reservationB = await reservationBResponse.json() as { id: string };
 const customerEmail = `reservation-renter-a-${stamp}@example.test`;
 expect((await request.post(`${api}/auth/customer/register`, { data: { email: customerEmail, password } })).status()).toBe(201);
 const customerVerification = await latestToken(request, customerEmail, 'EMAIL_VERIFICATION');
 expect((await request.post(`${api}/auth/verify-email`, { data: { token: customerVerification } })).status()).toBe(204);
 const renter = await login(request, customerEmail, 'CUSTOMER');
 const renterHeaders = { authorization: `Bearer ${renter.accessToken}` };
 const renterBookings = await request.get(`${api}/customer/bookings`, { headers: renterHeaders }).then((response) => response.json()) as Array<{ id: string; business: { name: string } }>;
 expect(renterBookings.map((booking) => booking.id)).toContain(firstReservation.id);
 expect(renterBookings.map((booking) => booking.id)).not.toContain(reservationB.id);
 expect((await request.get(`${api}/business/reservations`, { headers: renterHeaders })).status()).toBe(403);
 await page.goto('/portal/login');
 await page.getByLabel('Email').fill(customerEmail);
 await page.getByLabel('Password').fill(password);
 await page.getByRole('button', { name: 'Sign in' }).click();
 await expect(page).toHaveURL(/\/portal/);
 await expect(page.getByRole('heading', { name: 'Your rentals, in one place.' })).toBeVisible();
 await expect(page.getByText('Toyota Availability A').first()).toBeVisible();
 await expect(page.getByText('Honda Availability B')).toHaveCount(0);
 expect((await request.patch(`${api}/business/reservations/${reservationB.id}/status`, { headers: headersB, data: { status: 'CONFIRMED' } })).status()).toBe(200);
 expect((await request.patch(`${api}/business/reservations/${reservationB.id}/status`, { headers: headersB, data: { status: 'READY_FOR_PICKUP' } })).status()).toBe(200);
 const rentalBResponse = await request.post(`${api}/business/reservations/${reservationB.id}/convert-to-rental`, { headers: headersB });
 expect(rentalBResponse.status()).toBe(201);
 const rentalB = await rentalBResponse.json() as { id: string };
 const paymentPath = `${api}/business/reservations/${firstReservation.id}/payments`;
 const depositPath = `${api}/business/reservations/${firstReservation.id}/deposits`;
 expect((await request.post(paymentPath, { headers: headersA, data: { type: 'RECEIVED', amountMinor: 200000, method: 'EASYPAISA', reference: 'TEST-RECEIPT', businessId: tokenB.user.businessId } })).status()).toBe(201);
 expect((await request.post(paymentPath, { headers: headersA, data: { type: 'REFUNDED', amountMinor: 200001, method: 'CASH' } })).status()).toBe(409);
 expect((await request.post(paymentPath, { headers: headersA, data: { type: 'REFUNDED', amountMinor: 50000, method: 'BANK_TRANSFER', reference: 'TEST-REFUND' } })).status()).toBe(201);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'COLLECTED', amountMinor: 400000, reason: 'Collected at pickup' } })).status()).toBe(201);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'REFUNDED', amountMinor: 400001, reason: 'Over-balance refund check' } })).status()).toBe(409);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'RETAINED', amountMinor: 100000, reason: 'Late return charge' } })).status()).toBe(201);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'REFUNDED', amountMinor: 200000, reason: 'Remaining deposit returned' } })).status()).toBe(201);
 const ledger = await request.get(`${api}/business/reservations/${firstReservation.id}/ledger`, { headers: headersA }).then((response) => response.json()) as { paymentTotalMinor: number; depositHeldMinor: number };
 expect(ledger.paymentTotalMinor).toBe(150000);
 expect(ledger.depositHeldMinor).toBe(100000);
 const ownList = await request.get(`${api}/business/reservations`, { headers: headersA }).then((response) => response.json()) as Array<{ id: string }>;
 expect(ownList.map((reservation) => reservation.id)).toContain(firstReservation.id);
 expect(ownList.map((reservation) => reservation.id)).not.toContain(reservationB.id);
 expect((await request.get(`${api}/business/reservations/${reservationB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.get(`${api}/business/reservations/${reservationB.id}/ledger`, { headers: headersA })).status()).toBe(404);
 expect((await request.post(`${api}/business/reservations/${reservationB.id}/payments`, { headers: headersA, data: { type: 'RECEIVED', amountMinor: 1000, method: 'CASH' } })).status()).toBe(404);
 expect((await request.get(`${api}/business/rentals`, { headers: headersA })).status()).toBe(200);
 expect((await request.get(`${api}/business/rentals/${rentalB.id}`, { headers: headersA })).status()).toBe(404);
 expect((await request.patch(`${api}/business/reservations/${reservationB.id}/status`, { headers: headersA, data: { status: 'CANCELLED', reason: 'cross tenant check' } })).status()).toBe(404);
 expect((await request.get(`${api}/business/reservations/guessed-reservation-id`, { headers: headersA })).status()).toBe(404);
 expect((await request.post(`${api}/business/reservations`, { headers: headersA, data: { ...reservationPayload, vehicleId: vehicleB.id } })).status()).toBe(404);
 const conversion = await request.post(`${api}/business/reservations/${firstReservation.id}/convert-to-rental`, { headers: headersA });
 expect(conversion.status()).toBe(201);
 const rental = await conversion.json() as { id: string; vehicleId: string; status: string; estimatedTotalMinor: number };
 expect(rental.status).toBe('BOOKED');
 const reportFrom = new Date(startAt.getTime() - 86400000).toISOString();
 const reportTo = new Date(endAt.getTime() + 86400000).toISOString();
 const reportQuery = new URLSearchParams({ from: reportFrom, to: reportTo });
 const reportA = await request.get(`${api}/business/reports/utilization?${reportQuery}`, { headers: headersA }).then((response) => response.json()) as { vehicles: Array<{ id: string }>; fleetUtilizationPercent: number };
 const reportB = await request.get(`${api}/business/reports/utilization?${reportQuery}`, { headers: headersB }).then((response) => response.json()) as { vehicles: Array<{ id: string }> };
 expect(reportA.vehicles.map((vehicle) => vehicle.id)).toEqual([vehicleA.id]);
 expect(reportA.fleetUtilizationPercent).toBe(50);
 expect(reportB.vehicles.map((vehicle) => vehicle.id)).toEqual([vehicleB.id]);
 const searchQuery = `Toyota Availability A ${stamp}`;
 const searchA = await request.get(`${api}/business/search?query=${encodeURIComponent(searchQuery)}`, { headers: headersA }).then((response) => response.json()) as { results: Array<{ id: string; title: string }> };
 const searchB = await request.get(`${api}/business/search?query=${encodeURIComponent(searchQuery)}`, { headers: headersB }).then((response) => response.json()) as { results: Array<{ id: string; title: string }> };
 expect(searchA.results.some((result) => result.id === vehicleA.id)).toBe(true);
 expect(searchB.results).toHaveLength(0);
 expect((await request.get(`${api}/business/search?query=x`, { headers: headersA })).status()).toBe(400);
 expect((await request.get(`${api}/business/search?query=${encodeURIComponent(searchQuery)}`, { headers: renterHeaders })).status()).toBe(403);
 const utilizationCsv = await request.get(`${api}/business/reports/utilization/export.csv?${reportQuery}`, { headers: headersA });
 expect(utilizationCsv.status()).toBe(200);
 expect(utilizationCsv.headers()['content-type']).toContain('text/csv');
 expect(await utilizationCsv.text()).toContain('Toyota Availability A');
 expect((await request.get(`${api}/business/rentals/${rental.id}`, { headers: headersB })).status()).toBe(404);
 expect((await request.patch(`${api}/business/reservations/${firstReservation.id}/status`, { headers: headersA, data: { status: 'CANCELLED', reason: 'Cannot cancel after conversion' } })).status()).toBe(409);
 expect((await request.post(`${api}/business/rentals/${rental.id}/checkout`, { headers: headersA, data: { odometerKm: 12000, fuelPercent: 80 } })).status()).toBe(409);
 expect((await request.post(depositPath, { headers: headersA, data: { type: 'COLLECTED', amountMinor: 400000, reason: 'Balance collected before handover' } })).status()).toBe(201);
 const clearChecklist = { exterior: 'OK', glass: 'OK', tires: 'OK', lights: 'OK', interior: 'OK', documents: 'OK', accessories: 'OK' };
 const upload = await request.post(`${api}/business/files`, { headers: headersA, multipart: { file: { name: 'handover.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/Y2cAAAAASUVORK5CYII=', 'base64') } } });
 expect(upload.status()).toBe(201);
 const evidenceAsset = await upload.json() as { id: string };
 const preHandover = await request.post(`${api}/business/inspections`, { headers: headersA, data: { vehicleId: rental.vehicleId, rentalId: rental.id, stage: 'PRE_HANDOVER', checklist: clearChecklist, odometerKm: 12000, fuelPercent: 80, evidenceAssetIds: [evidenceAsset.id] } });
 expect(preHandover.status()).toBe(201);
 const inspectionA = await preHandover.json() as { id: string };
 const ownInspections = await request.get(`${api}/business/inspections?vehicleId=${encodeURIComponent(rental.vehicleId)}`, { headers: headersA }).then((response) => response.json()) as Array<{ id: string; evidence: Array<{ fileAsset: { id: string } | null }> }>;
 expect(ownInspections.find((inspection) => inspection.id === inspectionA.id)?.evidence[0]?.fileAsset?.id).toBe(evidenceAsset.id);
 const evidenceDownload = await request.get(`${api}/business/files/${evidenceAsset.id}/download`, { headers: headersA });
 expect(evidenceDownload.status()).toBe(200);
 expect(evidenceDownload.headers()['content-type']).toContain('image/png');
 expect((await request.get(`${api}/business/files/${evidenceAsset.id}/download`, { headers: headersB })).status()).toBe(403);
 expect((await request.get(`${api}/business/inspections?vehicleId=${encodeURIComponent(rental.vehicleId)}`, { headers: headersB }).then((response) => response.json()) as Array<{ id: string }>).length).toBe(0);
 const checkout = await request.post(`${api}/business/rentals/${rental.id}/checkout`, { headers: headersA, data: { odometerKm: 12000, fuelPercent: 80, notes: 'Vehicle handover complete' } });
 expect(checkout.status()).toBe(201);
 expect((await checkout.json() as { status: string }).status).toBe('ACTIVE');
 const conflictingExtension = await request.patch(`${api}/business/rentals/${rental.id}/extension`, { headers: headersA, data: { expectedReturnAt: new Date(concurrentStart.getTime() + 86400000).toISOString(), reason: 'Test overlap prevention' } });
 expect(conflictingExtension.status()).toBe(409);
 const successfulExtension = await request.patch(`${api}/business/rentals/${rental.id}/extension`, { headers: headersA, data: { expectedReturnAt: new Date(endAt.getTime() + 86400000).toISOString(), reason: 'Renter requested one additional day' } });
 expect(successfulExtension.status()).toBe(200);
 const requestedReturnAt = new Date(endAt.getTime() + 28 * 60 * 60 * 1000);
 requestedReturnAt.setSeconds(0, 0);
 await page.goto('/portal');
 const requestedLocalTime = new Date(requestedReturnAt.getTime() - requestedReturnAt.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
 await page.getByLabel('Requested return date and time').fill(requestedLocalTime);
 await page.getByLabel('Why do you need more time?').fill('My return trip has been delayed by a day.');
 await page.getByRole('button', { name: 'Request more time' }).click();
 await expect(page.getByRole('status')).toContainText('request has been sent');
 await expect(page.getByText('pending', { exact: true })).toBeVisible();
 const ownerNotices = await request.get(`${api}/business/notifications`, { headers: headersA }).then((response) => response.json()) as Array<{ id: string; event: string; title: string | null }>;
 expect(ownerNotices.some((notice) => notice.event === 'RENTAL_EXTENSION_REQUEST' && notice.title === 'A renter requested more time')).toBe(true);
 const otherTenantNotices = await request.get(`${api}/business/notifications`, { headers: headersB }).then((response) => response.json()) as Array<{ id: string }>;
 expect(otherTenantNotices).toHaveLength(0);
 const ownerRequestNotice = ownerNotices.find((notice) => notice.event === 'RENTAL_EXTENSION_REQUEST')!;
 expect((await request.patch(`${api}/business/notifications/${ownerRequestNotice.id}/read`, { headers: headersB })).status()).toBe(404);
 const unreadTodayA = await request.get(`${api}/business/operations/today`, { headers: headersA }).then((response) => response.json()) as { unreadNotifications: number };
 const unreadTodayB = await request.get(`${api}/business/operations/today`, { headers: headersB }).then((response) => response.json()) as { unreadNotifications: number };
 expect(unreadTodayA.unreadNotifications).toBe(1);
 expect(unreadTodayB.unreadNotifications).toBe(0);
 const extensionRequests = await request.get(`${api}/business/rentals/extension-requests`, { headers: headersA }).then((response) => response.json()) as Array<{ id: string; rentalId: string }>;
 const extensionRequest = extensionRequests.find((entry) => entry.rentalId === rental.id)!;
 expect(extensionRequest).toBeTruthy();
 const concurrentReviews = await Promise.all([
  request.patch(`${api}/business/rentals/extension-requests/${extensionRequest.id}`, { headers: headersA, data: { approve: true, decisionNote: 'Vehicle remains available.' } }),
  request.patch(`${api}/business/rentals/extension-requests/${extensionRequest.id}`, { headers: headersA, data: { approve: true, decisionNote: 'Duplicate review attempt.' } }),
 ]);
 expect(concurrentReviews.map((response) => response.status()).sort()).toEqual([200, 404]);
 const renterNotices = await request.get(`${api}/customer/notifications`, { headers: renterHeaders }).then((response) => response.json()) as Array<{ event: string; title: string | null }>;
 expect(renterNotices.some((notice) => notice.event === 'RENTAL_EXTENSION_REVIEW' && notice.title === 'Return date request approved')).toBe(true);
 await page.reload();
 await expect(page.getByText('approved', { exact: true })).toBeVisible();
 await expect(page.getByRole('heading', { name: 'Updates' })).toBeVisible();
 await expect(page.getByText('Return date request approved')).toBeVisible();
 await page.getByRole('button', { name: 'Mark as read' }).first().click();
 await expect(page.getByRole('button', { name: 'Mark as read' })).toHaveCount(0);
 const blockedRequestResponse = await request.post(`${api}/customer/rentals/${rental.id}/extension-requests`, { headers: renterHeaders, data: { requestedReturnAt: new Date(concurrentStart.getTime() + 12 * 60 * 60 * 1000).toISOString(), reason: 'I need additional time to return the car safely.' } });
 expect(blockedRequestResponse.status()).toBe(201);
 const blockedRequest = await blockedRequestResponse.json() as { id: string };
 expect((await request.patch(`${api}/business/rentals/extension-requests/${blockedRequest.id}`, { headers: headersA, data: { approve: true } })).status()).toBe(409);
 const stillPending = await request.get(`${api}/customer/extension-requests`, { headers: renterHeaders }).then((response) => response.json()) as Array<{ id: string; status: string }>;
 expect(stillPending.find((entry) => entry.id === blockedRequest.id)?.status).toBe('PENDING');
 expect((await request.get(`${api}/business/rentals/${rental.id}`, { headers: headersA }).then((response) => response.json()) as { expectedReturnAt: string }).expectedReturnAt).toBe(requestedReturnAt.toISOString());
 await page.goto('/logout');
 await page.getByRole('button', { name: 'Sign out' }).click();
 await page.goto('/login');
 await page.getByLabel('Email').fill(ownerA);
 await page.getByLabel('Password').fill(password);
 await page.getByRole('button', { name: 'Sign in' }).click();
 await expect(page).toHaveURL(/\/dashboard\/onboarding/);
 await page.goto('/app/rentals');
 const blockedRequestCard = page.locator('.ant-card').filter({ hasText: 'I need additional time to return the car safely.' });
 await blockedRequestCard.getByRole('textbox').fill('The vehicle is booked shortly after your current return time.');
 await blockedRequestCard.getByRole('button', { name: 'Decline request' }).click();
 await expect(blockedRequestCard.getByText('declined')).toBeVisible();
 const declinedRequest = await request.get(`${api}/customer/extension-requests`, { headers: renterHeaders }).then((response) => response.json()) as Array<{ id: string; status: string; decisionNote: string | null }>;
 expect(declinedRequest.find((entry) => entry.id === blockedRequest.id)).toMatchObject({ status: 'DECLINED', decisionNote: 'The vehicle is booked shortly after your current return time.' });
 const noticesAfterDecline = await request.get(`${api}/customer/notifications`, { headers: renterHeaders }).then((response) => response.json()) as Array<{ title: string | null }>;
 expect(noticesAfterDecline.some((notice) => notice.title === 'Return date request declined')).toBe(true);
 const returnInspection = await request.post(`${api}/business/inspections`, { headers: headersA, data: { vehicleId: rental.vehicleId, rentalId: rental.id, stage: 'RETURN', checklist: clearChecklist, odometerKm: 12100, fuelPercent: 70 } });
 expect(returnInspection.status()).toBe(201);
 const checkin = await request.post(`${api}/business/rentals/${rental.id}/return`, { headers: headersA, data: { odometerKm: 12100, fuelPercent: 70, returnLocationId: locationA.id, notes: 'Returned for cleaning and inspection' } });
 expect(checkin.status()).toBe(201);
 const returnedRental = await checkin.json() as { status: string; vehicle: { condition: string }; endOdometerKm: number };
 expect(returnedRental.status).toBe('RETURNED');
 expect(returnedRental.endOdometerKm).toBe(12100);
 expect(returnedRental.vehicle.condition).toBe('PREPARATION');
 expect((await request.post(`${api}/business/rentals/${rental.id}/return`, { headers: headersA, data: { odometerKm: 12100, fuelPercent: 70, returnLocationId: locationA.id } })).status()).toBe(409);
 const damage = await request.post(`${api}/business/inspections/damage-cases`, { headers: headersA, data: { vehicleId: rental.vehicleId, rentalId: rental.id, inspectionId: inspectionA.id, title: 'Windshield chip', description: 'Small chip noticed during inspection.', estimatedMinor: 200000 } });
 expect(damage.status()).toBe(201);
 const damageCase = await damage.json() as { id: string; status: string };
 expect(damageCase.status).toBe('OPEN');
 expect((await request.patch(`${api}/business/inspections/damage-cases/${damageCase.id}`, { headers: headersA, data: { status: 'RESOLVED' } })).status()).toBe(400);
 expect((await request.patch(`${api}/business/inspections/damage-cases/${damageCase.id}`, { headers: headersB, data: { status: 'RESOLVED', resolutionNotes: 'Cross-tenant' } })).status()).toBe(404);
 expect((await request.patch(`${api}/business/inspections/damage-cases/${damageCase.id}`, { headers: headersA, data: { status: 'RESOLVED', resolutionNotes: 'Replaced windshield and checked the seal.' } })).status()).toBe(200);
 const settlementPath = `${api}/business/rentals/${rental.id}/settlement`;
 expect((await request.post(settlementPath, { headers: headersB, data: { additionalChargesMinor: 0, paymentReceivedMinor: 3_000_000, method: 'CASH' } })).status()).toBe(404);
 expect((await request.post(settlementPath, { headers: headersA, data: { additionalChargesMinor: 0, paymentReceivedMinor: 4_250_000, method: 'CASH' } })).status()).toBe(409);
 const settlement = await request.post(settlementPath, { headers: headersA, data: { additionalChargesMinor: 0, paymentReceivedMinor: 4_600_000, method: 'CASH', note: 'Rental balance received in full.' } });
 expect(settlement.status()).toBe(201);
 expect(await settlement.json()).toMatchObject({ rentalAmountMinor: 5_000_000, paymentReceivedMinor: 4_600_000, depositRetainedMinor: 250_000, depositRefundedMinor: 250_000 });
 const customerTransactions = await request.get(`${api}/customer/payments`, { headers: renterHeaders }).then((response) => response.json()) as Array<{ kind: string; type: string; vehicle: { make: string; model: string } }>;
 expect(customerTransactions.some((entry) => entry.kind === 'PAYMENT' && entry.type === 'RECEIVED' && entry.vehicle.model === 'Availability A')).toBe(true);
 expect(customerTransactions.some((entry) => entry.vehicle.model === 'Availability B')).toBe(false);
 const customerPage = await page.context().newPage();
 await customerPage.goto('/portal/login');
 await customerPage.getByLabel('Email').fill(customerEmail);
 await customerPage.getByLabel('Password').fill(password);
 await customerPage.getByRole('button', { name: 'Sign in' }).click();
 await expect(customerPage).toHaveURL(/\/portal/);
 await expect(customerPage.getByRole('heading', { name: 'Payments and deposits' })).toBeVisible();
 await expect(customerPage.getByText('Security deposit collected').first()).toBeVisible();
 await customerPage.close();
 expect((await request.get(`${api}/business/rentals/${rental.id}`, { headers: headersA }).then((response) => response.json()) as { status: string }).status).toBe('CLOSED');
 expect((await request.post(settlementPath, { headers: headersA, data: { additionalChargesMinor: 0, paymentReceivedMinor: 0, method: 'CASH' } })).status()).toBe(409);
 const issueChecklist = { ...clearChecklist, glass: 'ISSUE' };
 const issueInspection = await request.post(`${api}/business/inspections`, { headers: headersA, data: { vehicleId: rental.vehicleId, stage: 'RETURN', checklist: issueChecklist, odometerKm: 12100, fuelPercent: 70, notes: 'Small glass chip found.' } });
 expect(issueInspection.status()).toBe(201);
 const openCasesA = await request.get(`${api}/business/inspections/damage-cases`, { headers: headersA }).then((response) => response.json()) as Array<{ status: string }>;
 const openCasesB = await request.get(`${api}/business/inspections/damage-cases`, { headers: headersB }).then((response) => response.json()) as Array<{ status: string }>;
 expect(openCasesA.some((entry) => entry.status === 'OPEN')).toBe(true);
 expect(openCasesB).toHaveLength(0);
 expect((await request.get(`${api}/business/reservations`, { headers: { authorization: `Bearer ${tokenB.accessToken}` } })).status()).toBe(200);
});
