import Image from 'next/image';
import Link from 'next/link';
import { CallToAction, MarketingFrame } from '../components/marketing';
import { FaqAccordion } from '../components/faq-accordion';
import { ArrowRightOutlined, CarOutlined, CheckCircleFilled, ClockCircleOutlined, CreditCardOutlined, EnvironmentOutlined, FileDoneOutlined, UserOutlined } from '../components/marketing-icons';
import styles from './marketing.module.css';
import { jsonLd, pageMetadata } from '../lib/seo';

export const metadata = pageMetadata({ title: 'Car rental operations, in one clear workspace', description: 'Manage bookings, vehicles, customer handovers, returns and rental payments in one practical workspace for rental teams.', path: '/' });

const steps = ['Booking request', 'Review & confirm', 'Vehicle pickup', 'On rent', 'Return & inspect', 'Settle & ready'];
const previewFaq = [
  { key: 'trial', label: 'How long is the free trial?', children: <p>Every new business starts with a 30-day trial. You can add your team and setup details at your own pace.</p> },
  { key: 'booking', label: 'Can customers book online?', children: <p>Your hosted business page helps customers view your vehicles and send a request. Your team reviews availability before confirming.</p> },
  { key: 'technical', label: 'Do I need technical experience?', children: <p>No. Setup is guided, uses everyday rental language and lets you leave optional details until later.</p> },
];

export default function Home() {
  const organization = { '@context': 'https://schema.org', '@type': 'Organization', name: 'RentPay', url: process.env.WEB_URL ?? 'http://localhost:3000' };
  const software = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'RentPay', applicationCategory: 'BusinessApplication', operatingSystem: 'Web', description: 'A rental operations workspace for independent car-rental businesses.' };
  return <MarketingFrame><main id="main-content">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(organization) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(software) }} />

    <section className={styles.hero} aria-labelledby="hero-title"><div className={styles.heroInner}>
      <div className={styles.heroCopy}><span className={styles.eyebrow}><span className={styles.eyebrowDot} /> Rental operations, made clearer</span><h1 id="hero-title">Every rental.<br /><span>One clear path.</span></h1><p>Run bookings, vehicles, customers, payments and handovers from one workspace—so your whole team knows what happens next.</p>
        <div className={styles.heroActions}><Link className={styles.button} href="/register">Start your 30-day trial <ArrowRightOutlined aria-hidden="true" /></Link><Link className={styles.secondaryButton} href="/how-it-works"><span className={styles.playMark} aria-hidden="true">↗</span> See how RentPay works</Link></div>
        <div className={styles.heroTrust}><CheckCircleFilled aria-hidden="true" /><span>No card required to get started</span><span className={styles.trustDivider} /><span>Setup in a few guided steps</span></div>
        <div className={styles.operationRibbon} aria-label="Connected rental operations"><span>Booking</span><ArrowRightOutlined aria-hidden="true" /><span>Fleet</span><ArrowRightOutlined aria-hidden="true" /><span>Customer</span><ArrowRightOutlined aria-hidden="true" /><span>Payment</span><ArrowRightOutlined aria-hidden="true" /><span>Handover</span></div>
      </div>
      <div className={styles.heroStage}>
        <div className={styles.heroPhoto}><Image src="/images/marketing/silver-crossover-cutout.png" alt="Silver rental crossover shown from the side" fill priority sizes="(max-width: 768px) 100vw, 80vw" /></div>
        <div className={styles.heroPhotoCaption}><span>READY FOR PICKUP</span><span>Business-owned fleet</span></div>
        <div className={styles.todayPreview} aria-label="Illustrative RentPay daily operations preview"><div className={styles.previewHeading}><div><span className={styles.previewEyebrow}>A DAY IN RENTPAY</span><strong>Your next steps, together.</strong></div><span className={styles.previewAvatar}>RP</span></div>
          <div className={styles.previewNotice}><span className={styles.noticeIcon}><ClockCircleOutlined /></span><div><strong>Today at a glance</strong><span>Example workspace · 3 items need attention</span></div><ArrowRightOutlined aria-hidden="true" /></div>
          <div className={styles.previewTask}><span className={styles.taskIcon}><CarOutlined /></span><div><strong>Pickup · Corolla</strong><span>09:30 · Confirm handover details</span></div><span className={styles.taskStatus}>UP NEXT</span></div>
          <div className={styles.previewTask}><span className={`${styles.taskIcon} ${styles.taskIconInfo}`}><FileDoneOutlined /></span><div><strong>Return · City sedan</strong><span>11:00 · Inspection due</span></div><span className={styles.taskStatusMuted}>RETURN</span></div>
          <div className={styles.previewTask}><span className={`${styles.taskIcon} ${styles.taskIconGreen}`}><CreditCardOutlined /></span><div><strong>Payment follow-up</strong><span>Review the open balance</span></div><span className={styles.taskStatusMuted}>REVIEW</span></div>
          <div className={styles.previewFooter}><span><span className={styles.liveDot} /> All work in one place</span><span>Private workspace preview</span></div>
        </div>
        <div className={styles.floatingLocation}><EnvironmentOutlined aria-hidden="true" /><span>Pickup location</span><strong>Choose your own</strong></div>
      </div>
      <div className={styles.heroQuickCards} aria-label="Illustrative rental workspace overview"><div className={styles.heroQuickCard}><span>Booking requests</span><strong>Keep every enquiry in view</strong></div><div className={styles.heroQuickCard}><span>Vehicle readiness</span><strong>Know what can go out next</strong></div><div className={styles.heroQuickCard}><span>Return & settlement</span><strong>Close the rental clearly</strong></div></div>
    </div></section>

    <section className={styles.flowSection} aria-labelledby="flow-title"><div className={styles.sectionInner}><div className={styles.flowIntro}><span className={styles.eyebrow}>The rental, end to end</span><h2 id="flow-title">No more stitching the day together.</h2><p>Follow one rental from the first customer message until the vehicle is ready for its next trip.</p></div><ol className={styles.lifecycle}>{steps.map((label, index) => <li className={styles.lifeStep} key={label}><span className={styles.lifeNumber}>{String(index + 1).padStart(2, '0')}</span><span>{label}</span>{index < steps.length - 1 && <ArrowRightOutlined className={styles.lifeArrow} aria-hidden="true" />}</li>)}</ol><Link className={styles.inlineLink} href="/how-it-works">See the complete rental flow <ArrowRightOutlined aria-hidden="true" /></Link></div></section>

    <section className={styles.operationsSection} aria-labelledby="operations-title"><div className={styles.operationsInner}><div className={styles.operationsCopy}><span className={styles.eyebrow}>The work behind every handover</span><h2 id="operations-title">Give every teammate the same clear picture.</h2><p>Bring pickup plans, vehicle readiness, renter details and money follow-ups together—so staff spend less time checking different places.</p><ul className={styles.checkList}><li><CheckCircleFilled /> One daily view of what needs attention</li><li><CheckCircleFilled /> Clear vehicle and handover status</li><li><CheckCircleFilled /> Customer and payment details beside the rental</li></ul><Link className={styles.lightLink} href="/features">Explore the tools <ArrowRightOutlined aria-hidden="true" /></Link></div>
        <div className={styles.operationsBoard}><div className={styles.boardTop}><div><span className={styles.boardEyebrow}>TODAY · SAMPLE VIEW</span><strong>Rental team overview</strong></div><span className={styles.boardDate}>Operations</span></div><div className={styles.boardStatus}><span>Tuesday, 14 October</span><span className={styles.boardStatusPill}><span /> Running smoothly</span></div><div className={styles.boardTimeline}><div className={styles.timelineItem}><span className={styles.timelineTime}>09:30</span><span className={styles.timelineRail}><i /></span><div><strong>Customer pickup</strong><span>Corolla · Review documents and vehicle condition</span></div><span className={styles.timelineTag}>PICKUP</span></div><div className={styles.timelineItem}><span className={styles.timelineTime}>11:00</span><span className={styles.timelineRail}><i /></span><div><strong>Vehicle return</strong><span>City sedan · Record mileage and inspect</span></div><span className={`${styles.timelineTag} ${styles.timelineTagInfo}`}>RETURN</span></div><div className={styles.timelineItem}><span className={styles.timelineTime}>14:30</span><span className={styles.timelineRail}><i /></span><div><strong>Availability check</strong><span>Confirm the next requested dates</span></div><span className={`${styles.timelineTag} ${styles.timelineTagGreen}`}>FLEET</span></div></div><div className={styles.boardBottom}><span><UserOutlined /> Team workspace</span><span>Example data · not live bookings</span></div></div>
      </div></section>

    <section className={styles.fleetSection} aria-labelledby="fleet-title"><div className={styles.fleetInner}><div className={styles.fleetPhoto}><Image src="/images/marketing/fleet-handover.png" alt="A small fleet of well-maintained rental cars ready at a business location" fill sizes="(max-width: 768px) 100vw, 48vw" /><span className={styles.photoLabel}><CarOutlined /> Fleet visibility</span></div><div className={styles.fleetCopy}><span className={styles.eyebrow}>Fleet, without the guesswork</span><h2 id="fleet-title">Know which vehicle is ready before you promise it.</h2><p>Keep each vehicle’s location and rental status visible to the people coordinating the next booking.</p><div className={styles.vehicleRows}><div><span className={styles.vehicleThumb}><CarOutlined /></span><span><strong>Compact sedan</strong><small>Ready for the next booking</small></span><span className={styles.readyTag}>READY</span></div><div><span className={styles.vehicleThumb}><CarOutlined /></span><span><strong>Family crossover</strong><small>On rent · return expected today</small></span><span className={styles.rentedTag}>ON RENT</span></div><div><span className={styles.vehicleThumb}><CarOutlined /></span><span><strong>City hatchback</strong><small>Preparation check due</small></span><span className={styles.checkTag}>CHECK</span></div></div><Link className={styles.inlineLink} href="/features">See fleet and availability tools <ArrowRightOutlined aria-hidden="true" /></Link></div></div></section>

    <section className={styles.bookingSection} aria-labelledby="booking-title"><div className={styles.bookingInner}><div className={styles.bookingCopy}><span className={styles.eyebrow}>A better first step for renters</span><h2 id="booking-title">Make it easy to ask about the right car.</h2><p>Give your business a hosted page customers can open on any phone. They browse your vehicles, share dates and send a request—your team decides what’s available.</p><div className={styles.bookingFlow}><span><i>01</i>Choose dates</span><ArrowRightOutlined /><span><i>02</i>Explore vehicles</span><ArrowRightOutlined /><span><i>03</i>Request a booking</span></div><Link className={styles.secondaryButton} href="/features">See the customer journey <ArrowRightOutlined aria-hidden="true" /></Link></div><div className={styles.bookingMock}><div className={styles.bookingMockTop}><span className={styles.mockBrand}><span>R</span> Rental site preview</span><span className={styles.mockMenu}>Vehicles&nbsp;&nbsp; Contact</span></div><div className={styles.bookingMockHero}><div><span>YOUR NEXT DRIVE STARTS HERE</span><strong>Find a car that fits the trip.</strong></div><div className={styles.searchBar}><span>Pickup location</span><span>Pickup date</span><span>Return date</span><b>Find vehicles <ArrowRightOutlined /></b></div></div><div className={styles.carPreviewCard}><div className={styles.carPreviewImage}><Image src="/images/marketing/vehicle-booking.png" alt="Example rental sedan shown on a customer vehicle page" fill sizes="(max-width: 768px) 100vw, 360px" /></div><div className={styles.carPreviewDetails}><span className={styles.carCategory}>COMFORT · AUTOMATIC</span><strong>Everyday sedan</strong><span>Clear details. A simple request.</span><b>From your business <ArrowRightOutlined /></b></div></div><div className={styles.mockFooter}><CheckCircleFilled /> Your business reviews every request before confirming.</div></div></div></section>

    <section className={styles.financeSection} aria-labelledby="finance-title"><div className={styles.financeInner}><div className={styles.financeHeading}><span className={styles.eyebrow}>Rental details that stay connected</span><h2 id="finance-title">Keep the practical details close to the work.</h2><p>When the team can find the rental, vehicle, customer and payment notes together, follow-up takes fewer steps.</p></div><div className={styles.financeRows}><div className={styles.financeRow}><span className={styles.financeIcon}><UserOutlined /></span><div><strong>Customer & driver</strong><span>Contact details and rental history</span></div><span className={styles.rowMeta}>WITH THE RENTAL</span></div><div className={styles.financeRow}><span className={`${styles.financeIcon} ${styles.financeIconAccent}`}><CreditCardOutlined /></span><div><strong>Payment & deposit</strong><span>What was collected and what needs follow-up</span></div><span className={styles.rowMeta}>CLEARLY RECORDED</span></div><div className={styles.financeRow}><span className={`${styles.financeIcon} ${styles.financeIconGreen}`}><FileDoneOutlined /></span><div><strong>Inspection & return</strong><span>Condition notes and next vehicle status</span></div><span className={styles.rowMeta}>READY FOR REVIEW</span></div></div></div></section>

    <section className={styles.faqSection} aria-labelledby="faq-title"><div className={styles.faqInner}><div className={styles.faqHeading}><span className={styles.eyebrow}>Good to know</span><h2 id="faq-title">A few straight answers.</h2><p>More details for a confident first step.</p><Link className={styles.inlineLink} href="/faq">Visit all FAQs <ArrowRightOutlined aria-hidden="true" /></Link></div><FaqAccordion className={styles.faqCollapse} items={previewFaq} /></div></section>
    <CallToAction />
  </main></MarketingFrame>;
}
